### ISSUE TITLE
Can't Import OneNote Notes

### ISSUE THREAD

**Issue by HumanMus1c** [streetwriters/notesnook-importer#108]
Failed to get notebook (original error: uninitialized_public_client_application: You must call and await the initialize function before attempting to call any other MSAL API. For more visit: aka.ms/msaljs/browser-errors). (Request failed with status code: -1).

![image](https://github.com/streetwriters/notesnook-importer/assets/46023154/2d376826-90a8-473a-a176-5f64de92609c)

**Comment by thecodrr** [comment]
Should be fixed.
