### ISSUE TITLE
Rate limiting during OneNote import

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook-importer#15]
**Describe the bug**
During an import of my OneNote notebooks the network requests started to fail with HTTP error code 429 (rate limiting).

**To Reproduce**
1. Go to https://importer.notesnook.com/
2. Select OneNote importer
3. Login and consent
4. import begins
5. I checked network dev tools and it looks like _all_ requests to `graph.microsoft.com` started returning `429` http errors:
```
{
	"error": {
		"code": "20166",
		"message": "The app has issued too many requests on behalf of this user in a short time period.",
		"innerError": {
			"date": "2022-03-27T21:54:33",
			"request-id": "<redacted>",
			"client-request-id": "<redacted>"
		}
	}
}
```
NOTE: Import is actually still ongoing and at the "Transforming pages" phase, but will definitely not complete successfully given all the network errors.

**Expected behavior**
Import completes successfully

**Desktop (please complete the following information):**
- Firefox v98.0.2
- Notesnook Importer v1.2.1

**Additional context**
- I analyzed the network requests and it looks like I got a `429` http error response to requests # 292, 310, 646, and then EVERY request starting at # 938. I think I'm hitting the [documented OneNote service limits](https://docs.microsoft.com/en-us/graph/throttling#onenote-service-limits). I would guess that at first I'm occasionally hitting the per-minute limit but at some point I hit the per-hour rate limit of 800.
- The `Retry-After` http response header mentioned in the documentation is NOT present in my http responses.

**Ideas to fix it... I'm just brainstorming**
- Can more requests be batched up to reduce the amount sent?
- Handle a 429 error response by backing off before either retrying or sending the next request. The Importer just keeps making requests after a 429 error right now. This can use exponential backoff. Unfortunately it might need to wait >1hr given the OneNote limits, but I'd be okay with that?
- Allow me to import one notebook at a time. That way I could manually eventually import all my notebooks as long as no single notebook was over the rate limit.

**Comment by thecodrr** [comment]
@altano yes! give it a try in v2.1.2 of the Importer. It should work much better.
