### ISSUE TITLE
Failed to get sectionGroup (original error: The specified resource ID does not exist.). 

### ISSUE THREAD

**Issue by konradphoto** [streetwriters/notesnook-importer#37]
I get the following error when trying to import Microsoft OneNote notes using Notesnook Importer (v1.4.2).
`Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).`

**Comment by konradphoto** [comment]
I got 7 of these errors and I just checked with Oneonet - I have 7 notebooks in Onenote so there is a chance this error relates to notebooks.

**Comment by thecodrr** [comment]
Hey, you can ignore this error. It occurs when the importer is checking for any and all section groups inside OneNote notebooks. You should verify that the import got all your notes — it is possible that some notes might be missing because of Microsoft not exposing them via their API.
