### ISSUE TITLE
Cant import .enex files

### ISSUE THREAD

**Issue by carlosecpf** [streetwriters/notesnook-importer#39]
Hi, 

I am migrating from Evernote to Notesnoook but the app's importer fails to create a .zip file with any content in it. I tried several .ENEX files that I have, but the importer tool do note recognize a single note in them and shows  "1. errors ocurred"

How should I proceed? I have 33GB of notes on evernote spreadred across several ENEX files. I am trying to import a single ENEX file at a time.

![Screenshot from 2022-11-20 11 19 11](https://user-images.githubusercontent.com/118673600/202907459-c3d11fe1-5a4d-4fa5-bf93-828d3e65e41f.png)

**Comment by thecodrr** [comment]
Hey, I will be releasing a new version of the importer tomorrow that can deal with such huge imports easily.

**Comment by carlosecpf** [comment]
Thanks! looking forward to it. In order to use it, do I need to update my Notesnook app?

**Comment by thecodrr** [comment]
Should be fixed in v1.5.1
