### ISSUE TITLE
Evernote importer broken

### ISSUE THREAD

**Issue by bonnepioche** [streetwriters/notesnook-importer#49]
Hi Guys,

I am evaluating NotesNook and the Evernote importer is broken:
- I import a simple (almost empty) Evernote notebook in the Notesnook importer and I have the following error message:

>  1. TextDecoderStream is not defined

I am using the latest Evernote windows client to generate the .exex (version 10.50.10)

Happy bug hunting!

Patrick

**Comment by thecodrr** [comment]
Hey, which browser are you using?

**Comment by thecodrr** [comment]
This has been fixed.
