### ISSUE TITLE
Importer not processing

### ISSUE THREAD

**Issue by skooks777** [streetwriters/notesnook-importer#56]
I exported a notebook from Evernote. It was 58 MB. I uploaded it to the web-based importer and it identified 194 notes. When I clicked "download ZIP" it said it was processing 1 of 194 notes, but it never went further than that. I've tried it multiple times now.

**Comment by thecodrr** [comment]
Can you press Ctrl + Shift + I, switch to the Console tab, take a screenshot & then upload the screenshot here?

**Comment by skooks777** [comment]
![screenshot1](https://user-images.githubusercontent.com/9127117/214645480-3cca501a-9180-40df-a09b-d8e095bfada2.jpg)
![screenshot2](https://user-images.githubusercontent.com/9127117/214645483-a67a92df-5f25-42ce-8fb7-f5ec5e7c8cf0.jpg)
Here you go. The first screenshot is from when the Brave Shield was enabled, the second after I disabled it. I'm in the Brave desktop browser for Windows.

**Comment by thecodrr** [comment]
Should be fixed now.
