### ISSUE TITLE
Importer hangs on "Importing your notes"

### ISSUE THREAD

**Issue by mscheerer** [streetwriters/notesnook-importer#73]
![image](https://github.com/streetwriters/notesnook-importer/assets/7645128/cd516635-f6ea-45a0-854d-173316b8b855)

I am transferring my notes from Evernote to Notesnook and I appear to be having some issues with the Importer.

I can create the zip file from the .enex file which contains around 800 notes, but whenever I try to then import the resulting zip file to Notesnook, it always stops and freezes at 117 notes imported and just sits there. I have left it for over an hour and it never moves.

I have tried this several times and it is always the same.

**Comment by thecodrr** [comment]
@mscheerer you can see which note it is getting stuck at by opening the .zip file and finding the folder at 117 position.

Also try opening the developer console by pressing `Ctrl + Shift + I`. See [this guide](https://support.foxy.io/en_US/site-monitoring/opening-the-browser-developer-console) if that isn't working.

Take a screenshot of the Developer console and put it here so I can see what's the issue.

Sorry for the inconvenience.

**Comment by mscheerer** [comment]
The Developer console never really gave me any information.I followed your idea of checking the zip file and had to examine the metadata file to find out which message was proceeded at the position 117, because it does not process the folders in order.Once I found the offending file I removed it and then split the import i to more manageable chunks of 100 messages and managed to get everything imported.It was rather long winded, but thanks for your helpOn 20 May 2023, at 04:29, Abdullah Atta ***@***.***> wrote:﻿
@mscheerer you can see which note it is getting stuck at by opening the .zip file and finding the folder at 117 position.
Also try opening the developer console by pressing Ctrl + Shift + I. See this guide if that isn't working.
Take a screenshot of the Developer console and put it here so I can see what's the issue.
Sorry for the inconvenience.

**Comment by thecodrr** [comment]
What was different in the offending file?

**Comment by mscheerer** [comment]
Nothing really, it was a very old note and one that I realised could be deleted, so it was not really a problem.

It was a note with a Web Snippet, from the Evernote Website, but it was from 2010, otherwise nothing really special.

**Comment by thecodrr** [comment]
Should be fixed now.
