### ISSUE TITLE
Failed to get user encryption key. Cannot cache attachments. (Evernote)

### ISSUE THREAD

**Issue by Iceman248** [streetwriters/notesnook-importer#78]
I keep getting this error, tried to multiple times. It actually says Import successful. 1 errors occurred, but nothing has been imported.

Windows. 2.5.5-e7bcad2-desktop

**Comment by thecodrr** [comment]
Hi, please try logging out of Notesnook and trying again. Also check that you are connected to the Internet and that sync is working.

**Comment by Iceman248** [comment]
I wasn't even logged in, but once I am it seems to import notes, but then says "Cannot read properties of undefined (reading 'type')"

**Comment by Iceman248** [comment]
I noticed that it imported most of my notes, but is missing quite a few, so some worked, but the error indicated that some didn't, it seems.

**Comment by thecodrr** [comment]
@Iceman248 the Importer kind of requires that user be logged in (it can work without login but gets stuck with attachments). Please try again but this time when the error pops up do this:

1. Press Ctrl + Shift + I to open Browser Developer Tools
2. Switch to the Console tab in the newly poped up Developer Tools
3. You will see an error message in the Console (red and with the same wording)
4. Take a screenshot of it and upload it here.

**Comment by Iceman248** [comment]
<img width="395" alt="image" src="https://github.com/streetwriters/notesnook-importer/assets/16282747/ea195a10-f319-4aa6-b27f-e9cd960eb84a">

**Comment by thecodrr** [comment]
That's perfect! Thank you.

**Comment by thecodrr** [comment]
This has been fixed.
