### ISSUE TITLE
Import from Zoho does not work

### ISSUE THREAD

**Issue by sk8board** [streetwriters/notesnook-importer#80]
I have attempted to import from Zoho using the notesnook importer. 

I have exported from Zoho using html as well as znote and attempted to import twice, once with znote and once with html. Both times, the importer shows, "Import successful. 0 errors occured", but there is nothing imported.

**Comment by thecodrr** [comment]
Please read the importer guide: https://help.notesnook.com/importing-notes/import-notes-from-zoho-notebook
