### ISSUE TITLE
Joplin Import

### ISSUE THREAD

**Issue by BlueAlmonds** [streetwriters/notesnook-importer#86]
I attempted to create a zip file using the importer tool and received the following messages:
144 errors occured
1. You are out of storage space.
2. You are out of storage space.
3. You are out of storage space.
4. You are out of storage space.
5. You are out of storage space.
6. You are out of storage space.
7. You are out of storage space.
8. You are out of storage space.
9. You are out of storage space.
10. You are out of storage space.
11. You are out of storage space.
12. You are out of storage space.
13. You are out of storage space.
14. You are out of storage space.
15. You are out of storage space.
16. You are out of storage space.
17. You are out of storage space.
18. You are out of storage space.
19. You are out of storage space.
20. You are out of storage space.
21. You are out of storage space.
22. You are out of storage space.
23. You are out of storage space.
24. You are out of storage space.
25. You are out of storage space.
26. You are out of storage space.
27. You are out of storage space.
28. You are out of storage space.
29. You are out of storage space.
30. You are out of storage space.
31. You are out of storage space.
32. You are out of storage space.
33. You are out of storage space.
34. You are out of storage space.
35. You are out of storage space.
36. You are out of storage space.
37. You are out of storage space.
38. You are out of storage space.
39. You are out of storage space.
40. You are out of storage space.
41. You are out of storage space.
42. You are out of storage space.
43. You are out of storage space.
44. You are out of storage space.
45. You are out of storage space.
46. You are out of storage space.
47. You are out of storage space.
48. You are out of storage space.
49. You are out of storage space.
50. You are out of storage space.
51. You are out of storage space.
52. You are out of storage space.
53. You are out of storage space.
54. You are out of storage space.
55. You are out of storage space.
56. You are out of storage space.
57. You are out of storage space.
58. You are out of storage space.
59. You are out of storage space.
60. You are out of storage space.
61. You are out of storage space.
62. You are out of storage space.
63. You are out of storage space.
64. You are out of storage space.
65. You are out of storage space.
66. You are out of storage space.
67. You are out of storage space.
68. You are out of storage space.
69. You are out of storage space.
70. You are out of storage space.
71. You are out of storage space.
72. You are out of storage space.
73. You are out of storage space.
74. You are out of storage space.
75. You are out of storage space.
76. You are out of storage space.
77. You are out of storage space.
78. You are out of storage space.
79. You are out of storage space.
80. You are out of storage space.
81. You are out of storage space.
82. You are out of storage space.
83. You are out of storage space.
84. You are out of storage space.
85. You are out of storage space.
86. You are out of storage space.
87. You are out of storage space.
88. You are out of storage space.
89. You are out of storage space.
90. You are out of storage space.
91. You are out of storage space.
92. You are out of storage space.
93. You are out of storage space.
94. You are out of storage space.
95. You are out of storage space.
96. You are out of storage space.
97. You are out of storage space.
98. You are out of storage space.
99. You are out of storage space.
100. You are out of storage space.
101. You are out of storage space.
102. You are out of storage space.
103. You are out of storage space.
104. You are out of storage space.
105. You are out of storage space.
106. You are out of storage space.
107. You are out of storage space.
108. You are out of storage space.
109. You are out of storage space.
110. You are out of storage space.
111. You are out of storage space.
112. You are out of storage space.
113. You are out of storage space.
114. You are out of storage space.
115. You are out of storage space.
116. You are out of storage space.
117. You are out of storage space.
118. You are out of storage space.
119. You are out of storage space.
120. You are out of storage space.
121. You are out of storage space.
122. You are out of storage space.
123. You are out of storage space.
124. You are out of storage space.
125. You are out of storage space.
126. You are out of storage space.
127. You are out of storage space.
128. You are out of storage space.
129. You are out of storage space.
130. You are out of storage space.
131. You are out of storage space.
132. You are out of storage space.
133. You are out of storage space.
134. You are out of storage space.
135. You are out of storage space.
136. You are out of storage space.
137. You are out of storage space.
138. You are out of storage space.
139. You are out of storage space.
140. You are out of storage space.
141. You are out of storage space.
142. You are out of storage space.
143. You are out of storage space.
144. You are out of storage space.

**Comment by thecodrr** [comment]
> You are out of storage space.

That can mean you don't have space on disk or you need to change your browser.
