### ISSUE TITLE
Errors importing Evernote enex

### ISSUE THREAD

**Issue by re-mute** [streetwriters/notesnook-importer#87]
Trying to import:
![image](https://github.com/streetwriters/notesnook-importer/assets/103073247/9dc9f26c-d8c7-41b6-a229-abb14b63ef47)

Error message:
8 errors occured
1. network error
2. network error
3. network error
4. network error
5. network error
6. network error
7. network error
8. network error

Multiple previous, smaller, .enex files have been successful, some also split into multiple .enex files.

It seems, as a non-developer, related to the size.

**Comment by thecodrr** [comment]
@re-mute what browser are you using?

**Comment by thecodrr** [comment]
This should be fixed now.
