### ISSUE TITLE
Errors importing OneNote using Notesnook Importer

### ISSUE THREAD

**Issue by dm0328** [streetwriters/notesnook-importer#92]
After logging into my Microsoft Account and allowing it into Notesnook I tried to import my OneNote notebooks and notes. I recieived the following errors and was told 0 notes were found.

7 errors occured
1. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).
2. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).
3. Failed to get page content for page "benny school schedule" in Dave's Notebook > Quick Notes (Request failed with status code: 404).
4. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).
5. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).
6. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).
7. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).

**Comment by rd-su** [comment]
I also have these errors:

```
3 errors occured
1. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).
2. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).
3. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).
```
