### ISSUE TITLE
Cannot import from OneNote

### ISSUE THREAD

**Issue by trjanderson** [streetwriters/notesnook-importer#99]
1 errors occured
1. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).

Tried on Firefox & Edge. Disabled many privacy settings that may be blocking the importer. The import seems like it is reading the notes without issue, then prompts with this error.

**Comment by muromdx** [comment]
In my case:

**0 notes found**

4 errors occured:
1. Failed to get page content for page  (Request failed with status code: 404).
2. Failed to get page content for page  (Request failed with status code: 404).
3. Failed to get page content for page  (Request failed with status code: 404).
4. Failed to get sectionGroup (original error: Указанный идентификатор ресурса не существует.). (Request failed with status code: 404).

So, metadata.json in .zip file is empty:

`{"version":"1.0.0","notes":[]}`
